language: java
jdk: openjdk11
env:
  global:
  - secure: I+WTII50+/PB9tiG/SUaiOtv9CJ3amcqF+oc1Ko3S5EHA9sdZcYHeanHtqL3vrXrB3nSGewcuNApikLF3NrS3eMFjKgGU7dsjvCVEWlMMnrJ6XBHChliAn4GuLtPYK3lsdvsDOlY8+IlvaFsJSmBV1WcZHhZdtsuclCa8E4EtkizC2eb4tMFt8n0ackrepKWSzPwygvTlOU5mYZIaagh507iVUMvN1E2i/4Dd/gZ2h6ik0kgNMsEwePD3NVGwQGcP3cc+kyvt6bmSavnmfyYzHljhehafURCRPwCRAPQKMG4G/sVPoSX9CAnhs6CzeaeyXTTQxIZ7+rgha76dHqUO/2fkF5xJVf9/GpL9B3P3wP/SQPz12kB2aXi6F4G3pVjOOS1hGsbboTNcEd6xawxsi7ggYdp20ofC2gJkteyCBKh3/rBbXJAV1zm0I9uBz2JgXMeKONERaarTJiY8nxd/NHSrUU9IBXD9iuE3yZh0614LyZil6uaS4YED13WGYNw34nJgavey5q8UVuBqtt/uSQczdYmO2D6ernXfaefeJKGWe6N5piQLkx//SBbiUfE7YozRzAJvGHBw/d8+ChoCRPvFvy2alwhVRBzLKfkXYvdlaI2F6ZPVBdP4AAq0wiNc/qvhCxrX6dMszZ7RWvBa2tXBZ5r30MlmQEA+39eky8=
  - secure: xg5Rq7ZeeDWPoYawnGJKlbh9aRPlUUnAqwXMif99n4zYcZps2odomXw2akVWrAQnAwu9NbAE4oFwV3WM5fakTM2kpgFnqLManxY7Q/83y1Nn1CiaQhATRKyScStX7w9F1GlHAyRGqoAfWmiDyffHkDRPVLOnUXWIJ4nUI/Zw6Fkxe0c6iLzLK1REQka26hZWdBmh9Aa8GMoZVuxqetNZxDqyXtYHsYVDQHmZQXMsyBKoeWbysTvEiu3UWYmiBsuxgIFDP0roWhHxb1S6Q+7UlnRrLkthUHM5nxbWmbG7HWFX2eZwqTi4+fXTt+RV746guI5P3LVlXs9hucNGcZfx50m7b1NX9bBvhRTJoLYsbRuiA2qV+Qd5svxCqPamJIG4fJwVg0h2qdIHrvgnFyfgXDUoBYVSAzcPIEKCe6C5iSW6o06UdfDTWbqUiQjM/DxE9027voSZ6uwYQIAxk1z7Z6G/ypF74YDfXQrJBKppBTLlER1mRj2WUjQY2Hfcz4/0erGYM5xKMjx4SfT4S7rBxssvq6Pp8UQzkp0PX43grt6jAon6fgdlf7QFzOrNAEPWFfPkA4S4NS7td/93yZzNvBzBW1cDgpB+BoG9pMvbgK20puUI31GaynVCo3cFNT6Bx1sT5K63AEyJD3dos8ZRTnny+64lP90czOZMyRtPQuM=
install: skip
script: mvn --settings .mvn/settings.xml install && ([[ $TRAVIS_BRANCH != "master" ]] || mvn --settings .mvn/settings.xml -DskipTests=true deploy)
sudo: false
cache:
  directories: "$HOME/.m2"
branches:
  except: gh-pages
notifications:
  email: joerg.hohwiller@googlemail.com
